/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author Ricardo
 */
public class FrameInstrucciones extends javax.swing.JFrame {

    /**
     * Creates new form FrameInstrucciones
     */
    public FrameInstrucciones() {
        initComponents();
    }
    
    public void listenerButton (ActionListener listener){
        this.regresarInstruccionesButton.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarInstruccionesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1076, 710));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresarInstruccionesButton.setBackground(new java.awt.Color(0, 0, 102));
        regresarInstruccionesButton.setForeground(new java.awt.Color(255, 255, 255));
        regresarInstruccionesButton.setText("Regresar");
        getContentPane().add(regresarInstruccionesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 160, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Instrucciones.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1080, 1080));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regresarInstruccionesButton;
    // End of variables declaration//GEN-END:variables
}
