/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Personajes;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Ricardo
 */
public class FrameLaberinto extends javax.swing.JFrame {

    /**
     * Creates new form FrameLaberinto
     */

    public FrameLaberinto() {
        initComponents();
    }

    public Laberinto getLaberinto1() {
        return laberinto1;
    }

    public void setLaberinto1(Laberinto laberinto1) {
        this.laberinto1 = laberinto1;
    }

    public JLabel getMensajesLabel() {
        return mensajesLabel;
    }

    public void setMensajesLabel(JLabel mensajesLabel) {
        this.mensajesLabel = mensajesLabel;
    }
    
    


    public Laberinto panelLab() {
        return this.laberinto1;
    }

    public void listenerButton(ActionListener listener) {
        this.regresarButton.addActionListener(listener);
    }

    public void listenKey(KeyListener listener) {
        panelLab().addKeyListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarButton = new javax.swing.JButton();
        laberinto1 = new View.Laberinto();
        mensajesLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 810));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresarButton.setBackground(new java.awt.Color(51, 153, 255));
        regresarButton.setText("Regresar");
        getContentPane().add(regresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, -1, -1));

        mensajesLabel.setBackground(new java.awt.Color(255, 153, 153));
        mensajesLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mensajesLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mensajesLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        laberinto1.add(mensajesLabel);
        mensajesLabel.setBounds(850, 340, 160, 280);

        getContentPane().add(laberinto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LaberintoFinal.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private View.Laberinto laberinto1;
    private javax.swing.JLabel mensajesLabel;
    private javax.swing.JButton regresarButton;
    // End of variables declaration//GEN-END:variables
}
